# Server
quarkus.http.port=8081

# PostgreSQL reactive
quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=postgresql://postgres:5432/skymiles
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASS}
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Kafka
mp.messaging.outgoing.travel-confirmation.connector=smallrye-kafka
mp.messaging.outgoing.travel-confirmation.topic=travel-confirmation
mp.messaging.outgoing.travel-confirmation.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}

# REST Client
com.skymiles.client.MilesClient/mp-rest/url=http://miles-service:8082

# Logging
quarkus.log.console.json=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%X{request-id}] %c{2.} - %m%n
